import { mkdir, writeFile } from "node:fs/promises";
import { buildReportDraft } from "../src/domain/report.mjs";
import { renderReportDocx, renderReportPdf } from "../src/services/report-renderer.mjs";

const output = process.argv[2] || "/private/tmp/silverarch-report-qa";
const caseItem = {
  id: "fixture-formal-report", createdAt: "2026-06-22T10:00:00.000Z", contact: { phone: "+6591234567" },
  officerProfile: { name: "Alicia Lim", designation: "Social Assistance Officer", sso: "Bedok Social Service Office" },
  transcript: { text: "My name is Bobby. I am thirty-five years old and Singaporean. I was a Grab driver but injured my back. I am the sole breadwinner and my household income is basically zero because I am on MC. I have two children aged nine and ten. I need help with medical bills.", originalText: "My name is Bobby. I am thirty-five years old and Singaporean. I was a Grab driver but injured my back. I am the sole breadwinner and my household income is basically zero because I am on MC. I have two children aged nine and ten. I need help with medical bills.", editedText: "My name is Bobby. I am thirty-five years old and Singaporean. I was a Grab driver but injured my back. I am the sole breadwinner and my household income is currently zero because I am on medical leave. I have two children aged nine and ten. I need help with medical bills.", asrEngine: "elevenlabs", languageCode: "en" },
  translation: { status: "not-required" }, callerProfile: { officerSummary: "The applicant is a 35-year-old Singapore citizen and sole breadwinner with two school-aged children. He reports a back injury, current medical leave, no household income and difficulty meeting medical and household expenses." },
  factReviews: { citizenship: { status: "verified", value: "Singapore Citizen" }, applicantAge: { status: "verified", value: "35" }, householdIncome: { status: "verified", value: "S$0 currently reported" }, householdSize: { status: "unknown", explanation: "The total household size was not confirmed during intake" }, employment: { status: "verified", value: "Grab driver; currently on medical leave" } },
  consolidation: { presentingCircumstances: "The applicant reports that a back injury has interrupted his work as a private-hire driver. As the sole breadwinner, he currently reports no household income while supporting two children aged nine and ten. He also reports difficulty meeting medical bills and routine household expenses.", assessment: "The testimony indicates an abrupt income interruption with medical and dependent-care pressures. Citizenship and applicant age were verified from the reviewed testimony. Total household size remains unverified and should be confirmed before any scheme assessment is completed.", recommendedFollowUp: "Contact the applicant to confirm household composition, supporting medical documentation, current employment status and the duration of medical leave. Review supporting income and expense documents and assess the household against the relevant scheme criteria.", safeguardsResolution: "No immediate danger, self-harm or active family-violence indicators were detected. The officer reviewed the available transcript and timestamped evidence." },
  reviewAcknowledgements: { transcriptReviewed: true, flagsReviewed: true, declaration: true }, piiProposals: [], urgency: { urgent: false }, reviewReasons: ["Triage requires officer review"],
  triage: { shortlist: [{ schemeId: "smta", name: "ComCare Short-to-Medium-Term Assistance", softScore: "borderline", officerReasoning: "The reported work interruption, zero current income and sole-breadwinner responsibilities are relevant to an SMTA assessment. Eligibility must be determined after documentary and household verification.", appealRelevant: ["Medical burden mentioned", "Job loss mentioned"], insufficientInformation: ["Total household size not stated"], evidenceRefs: [] }, { schemeId: "chas", name: "Community Health Assist Scheme (CHAS)", softScore: "likely relevant", officerReasoning: "The applicant reports medical expenses and Singapore citizenship. An officer should verify current CHAS status and the appropriate subsidy tier.", appealRelevant: ["Medical burden mentioned"], insufficientInformation: [], evidenceRefs: [] }] },
  evidence: [{ category: "age", label: "Age", text: "thirty-five years old", start: 2.9, sentenceStart: 2.1 }, { category: "citizenship", label: "Citizenship / residency", text: "Singaporean", start: 5, sentenceStart: 2.1 }, { category: "income", label: "Income and finances", text: "sole breadwinner", start: 17.5, sentenceStart: 14 }, { category: "income", label: "Income and finances", text: "basically zero", start: 20.5, sentenceStart: 14 }, { category: "employment", label: "Employment", text: "on MC", start: 23.4, sentenceStart: 14 }, { category: "family", label: "Household and children", text: "two children aged nine and ten", start: 25.1, sentenceStart: 24.6 }, { category: "medical", label: "Health and medical needs", text: "medical bills", start: 30.7, sentenceStart: 29.8 }]
};

const report = { ...buildReportDraft(caseItem, 1, "2026-06-22T11:00:00.000Z"), status: "finalized", finalizedAt: "2026-06-22T11:05:00.000Z" };
await mkdir(output, { recursive: true });
await Promise.all([writeFile(`${output}/SilverArch-report.docx`, await renderReportDocx(report)), writeFile(`${output}/SilverArch-report.pdf`, await renderReportPdf(report))]);
console.log(output);
